### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by BennyDioxide** [QuiltMC/developer-wiki#18]
**What would you like the wiki to cover?**
I hope that the wiki can have more languages.

**Why should this be added to the wiki?**
To make more people easier to read the docs.

**Where in the wiki should this go?**
It may put in footer or the right up corner.
I recommend use crowdin for community translating.

**Comment by OroArmor** [comment]
As for now, I don't think this is a high priority for Quilt to work on for many reasons:
1. The way the wiki is currently designed doesn't really support the idea of multiple languages, but it could be done
2. All of Quilt's documentation and communication is in English, making this somewhat difficult.
3. Most programming is also done in English
4. Any page translators might work, but I haven't tried that.
5. The User wiki will support multiple languages, since that is needed more there

I will leave this issue open because this is something that *could* be done in the future, but is an extremely low priority.

**Comment by BennyDioxide** [comment]
I know.
Thanks for your reply!

**Comment by junepark678** [comment]
I would be interested in supporting this. I am a native speaker of Korean and would be happy to help with this long term project.

**Comment by LaylaMeower** [comment]
We'll be happy to translate to Hebrew if needed! (It's RTL, btw)
